### ISSUE TITLE
Add test / se for estimated parameters in PLN

### ISSUE THREAD

**Issue by mahendra-mariadassou** [PLN-team/PLNmodels#10]
Implement score test score and/or Wald test to test significance of model parameters. Stick with univariate tests for the time being.

**Comment by mahendra-mariadassou** [comment]
As of af761b53098460d826e44456275fbff68315fb15, there are now `fisher` and `standard_error` S3 methods to compute a variational approximation of the Fisher information matrix and the corresponding standard errors for the model parameters. 
Additional (empirical) work is needed to ensure that the corresponding tests / confidence intervals have proper Type I error / coverage

**Comment by jchiquet** [comment]
For the record, a conversation below between @mahendra-mariadassou and Stephane. It implies that

- we must clarify the documentation about Ficher and se of the coefficient
- we must double check the "divided-by-n" thing
- we should keep in mind the related Issue #30 to have a relevant interface in PLNmodels through `vcov`

> Fisher returns I(\theta) and for iid data, we usually have  I_n(\theta) = n*I(\theta) 
> As a result, it must be multiplied by n before it is reversed (or divided by n).  by n after inverting it) to have the asymptotic variance of  \hat{\theta}. If you just reverse, you'll have the variance of \sqrt{n} 
\hat{\theta}.
But if you just want to make univariate confidence intervals, you  can use `standard_error` which directly returns the standard deviation of each of the coefficients of \theta. The function multiplies fisher by n, Conversely, retrieves the diagonal and reorganizes it into a matrix of 
so that standard_error(myPLN)[i, j] returns the standard deviation of the estimator from coefficients(myPLN)[i, j]

**Comment by jchiquet** [comment]
Since version 1.0.0, variance estimation can be made for PLNfit either with jackknife or bootstrap. The variational approximation being too rough, we suppressed the direct interface to variational-based Fisher information matrix for estimating the variance (and the standard error).
