### ISSUE TITLE
Pb in the dimension of S for spherical model

### ISSUE THREAD

**Issue by scj-robin** [PLN-team/PLNmodels#79]
It seems that the matrix S returned by PLN has only one column for spherical covariance:

load('BarentsFish.Rdata')
fit <- PLN(count ~ 1, data=Data, control=list(covariance='spherical'))
dim(fit$var_par$S)
fit <- PLN(count ~ 1, data=Data, control=list(covariance='diagonal'))
dim(fit$var_par$S)

**Comment by jchiquet** [comment]
Indeed, since the spherical model has just one parameter to describe the covariance matrix, the variational distribution used in different from the diagonal and fully parametrized model: for individual i, we use q(z_i) ~ N(m_i, s_i I_p) where m_i is a vector in R^p (the p variables)  and s_i a scalar (we do not need p variational parameters to estimate a single model parameter right?).

So a matrix S with size n x 1 is expected for this model.

**Comment by scj-robin** [comment]
I thought that spherical was referring to Sigma. Does it imply that all S_i are spherical as well?

**Comment by jchiquet** [comment]
Indeed, spherical refers to Sigma. I don't now if it necessarily implies that the corresponding variational parameters in the approximation is spherical too. It is just that it sounded better this way, and more computationally efficient (the common rule being one model parameters = one variational parameters per sample).

**Comment by jchiquet** [comment]
@scj-robin We now use the same variational distribution to approximate any type of covariance structure (spherical, diagonal, full) for consistency
