### ISSUE TITLE
the formula in PLNnetwork to recover simulated network

### ISSUE THREAD

**Issue by lilythepooh** [PLN-team/PLNmodels#83]
Dear PLN-team,

Thanks for reading this message. I am testing PLNnetwork.R on a simulated dataset as below:
row(Z) follows Multivariate-Normal(0,Sigma)
Y follows Poisson(exp(Z+O))
```
library(PLNmodels)
library(MASS)
library(pracma)
library(corrplot)
p=20
n=30
O=matrix(0,nrow=n,ncol=p)
ocol=rnorm(n)
for (i in 1:p){
  O[,i]=ocol
}
R1=matrix(rnorm(p*p),nrow=p,ncol=p)
Psi=t(R1)%*%R1
Sigma=inv(Psi)
Z=matrix(0,nrow=n,ncol=p)
for (i in 1:n){
 Z[i,]=mvrnorm(n=1,rep(0,p),Sigma) 
}
Y=matrix(0,nrow=n,ncol=p)
for (i in 1:n){
  for (j in 1:p)
  {Y[i,j]=rpois(1,exp(O[i,j]+Z[i,j]))}}
simd<-prepare_data(counts=Y,covariates=matrix(0,nrow=nrow(O),ncol=ncol(O)),offset=O)
myPLNnetwork_row <- PLNnetwork(Abundance ~ 0+offset(Offset), data = simd)
```
I am wondering if it is right to write the formula `Abundance~0+offset(Offset)` here? The element in my matrix O is not all positive, so I did not use `log` for the offset. Would the package understand the formula `Abundance~0+offset(Offset)` as the model "Y follows Poisson(exp(Z+O))"? 

Thanks again for your time. I am looking forward to your reply.

Best wishes,
Sijia

**Comment by mahendra-mariadassou** [comment]
Hi Sijia, 

In the example you provided, it's completely correct to use `Abundance ~ 0+offset(Offset)` as your offsets are already in logarithmic scale. This is explicit in the generating process Y ~ Poisson(exp(Z+O)). 

We generally don't known the offsets and estimate them using an implicit model of the form Y ~ Poisson(Oexp(Z)), hence the `+ offset(log(Offset))` in the formula. 

The only point of attention I have is that the diagonal coefficients of Sigma should be roughly of order 1/p (as E[Psi] = pI_p) and that Z is centered so that the entries Y ~ Poisson(exp(Z + O)) should be on average exp(1/2p) and thus quite small. You may want to tweak O a bit to produce higher counts. 

You may want to consider `rPLN()` (documented [here](https://pln-team.github.io/PLNmodels/reference/rPLN.html)) to produce PLN counts when specifying the expected sum of counts for each sample. 

Best
Mahendra

**Comment by lilythepooh** [comment]
Dear Mahendra,

Thanks a lot for your early reply.

I changed the data generating code according to your advice:
```
library(PLNmodels)
library(MASS)
library(pracma)
library(corrplot)
p=20
n=30
#B=matrix(0,nrow=p,ncol=n)
#O=matrix(0,nrow=n,ncol=p)
#ocol=rnorm(n)
#for (i in 1:p){
 # O[,i]=ocol
#}
R1=matrix(rnorm(p*p),nrow=p,ncol=p)
Psi=t(R1)%*%R1
Sigma=inv(Psi)
Sigma=Sigma/mean(diag(Sigma))
Sigma=Sigma*(1/p)
Z=matrix(0,nrow=n,ncol=p)
for (i in 1:n){
 Z[i,]=mvrnorm(n=1,rep(0,p),Sigma) 
}
O=log(1000*matrix(1,nrow=nrow(Z),ncol=ncol(Z)))-log(rowSums(exp(rep(1,n)%o%diag(Sigma)/2)))
Y=matrix(0,nrow=n,ncol=p)
for (i in 1:n){
  for (j in 1:p)
  {Y[i,j]=rpois(1,exp(O[i,j]+Z[i,j]))}}
simd<-prepare_data(counts=Y,covariates=matrix(0,nrow=nrow(O),ncol=ncol(O)),offset=O)
myPLNnetwork_row <- PLNnetwork(Abundance ~ 0+offset(Offset), data = simd)
model_StARS <- getBestModel(myPLNnetwork_row, "StARS")
```
Is this what you had in mind?

By the way, could you please tell me where in the calculation or the paper is the assumption of "E(Psi)=pl_p"? I would like to understand why.

Thanks again for your time. Have a good day!

Best wishes,
Sijia

**Comment by mahendra-mariadassou** [comment]
Dear Sijia, 

This is indeed close to what I had in mind (you now aim for an average of 1000 reads per samples). 

The equality E(Psi)=pl_p is not an assumption but arises from the way you simulate Psi. Each entry of R1 is a standard gaussian. 
- Psi[i, i] is therefore a sum of p squared standard gaussian (a.k.a chi-square with p degrees of freedom) and thus E(Psi[i, i]) = p
- Psi[i, j] is a sum of terms X_k Y_k where X_k and Y_k are independent standard gaussians, and thus E(Psi[i, j]) = p

**Comment by lilythepooh** [comment]
Dear Mahendra,

Thanks a lot for your early reply and your patience.

Have a wonderful day!

best wishes,
Sijia
