### ISSUE TITLE
Difference between $scores and $project in PLNPCA

### ISSUE THREAD

**Issue by diegoisaias** [PLN-team/PLNmodels#84]
Hi,

I want to use PLNPCA for dimension reduction. My train data size is aprox 600 x 500 and it is sparse. The problem I have is that $project and $scores are very different in train data, so I can not apply the reduction in new data as I would like.

**Comment by mahendra-mariadassou** [comment]
Hi, 

Thanks for detecting and pointing out the bug. It mostly stemmed from a degenerate starting point for the projection step that lead to unexpected (and unwanted) behaviour. Using a smarter starting point leads to much more similar results for `$scores` and `$project` as illustrated below on your data. 

```
> library(PLNmodels)
This is packages 'PLNmodels' version 0.11.5-9020
Use future::plan(multicore/multisession) to speed up PLNPCA/PLNmixture/stability_selection.
> L6dataX <- read.csv("L6dataX.csv", header=FALSE)
> L6dataX = as.data.frame(L6dataX*100)  # (counts)
> L6dataY <- as.data.frame(read.csv("L6dataY.csv", header=FALSE))
> data = prepare_data(counts = L6dataX, covariates =  L6dataY)
> # Fit PLNPCA model of rank 3
> PCA_models = PLNPCA(Abundance ~ 1 + offset(log(Offset)), data, ranks = 3)

 Initialization...

 Adjusting 1 PLN models for PCA analysis.
	 Rank approximation = 3 
 Post-treatments
 DONE!
> model <- PCA_models$getBestModel()
> # Score and projections
> scores = model$scores
> proj = model$project(newdata = data)
```
You shouldn't expect values in scores and proj to be identical due to potential convergence issues (especially on very sparse data such as yours) but they are now highly similar:
```
> head(scores)
         PC1        PC2        PC3
1  472.56995 -173.27045  74.982400
2  102.17374 -205.98347  -5.002778
3 -196.60324 -124.71400 -84.701007
4 -241.89436  116.94053  83.476824
5   82.92962 -213.79105 -29.937907
6 -262.76301  -76.30728 -94.704663
> head(proj)
         PC1       PC2        PC3
1  470.35736 -172.8798  76.056568
2  101.80184 -205.4839  -4.388036
3 -195.71731 -124.3630 -84.646672
4 -241.11694  117.1821  83.387423
5   83.42561 -213.3753 -29.585044
6 -262.09784  -75.8386 -94.573745
```
as also shown here:
![scores_vs_proj](https://user-images.githubusercontent.com/2323508/120862641-93745c00-c589-11eb-9fad-16ae813b7290.png)

The latest version of the master branch should fix the issue.
